### ISSUE TITLE
Module still locks up when idle for just a few minutes

### ISSUE THREAD

**Issue by EnergeticStick** [bitfocus/companion-module-ptzoptics-visca#22]
The module completely stops working after being idle for only half an hour or so.  This issue has been present for quite a while and still hasn't been fixed.

**Comment by insight2learn** [comment]
This is very frustrating - only work around I have found is to STOP - START Companion again
Can this please be fixed?

many thanks

**Comment by insight2learn** [comment]
This looks like same issue #20

**Comment by jswalden** [comment]
Like I commented in #20, I can't reproduce this with the current module and don't have any explanation why the module would be locking up after just sitting idle, when it isn't doing any ongoing work.  Feel free to reopen if you can manage to get this to consistently reproduce with a recent version of the module.
