### ISSUE TITLE
Migrating to V3

### ISSUE THREAD

**Issue by tonypiper** [bitfocus/companion-module-ptzoptics-visca#25]
Hello. What's the status of this module? 

I have some PTZOptics clone cameras and I wanted to try out some features of Companion V3 Beta. However, I noticed that this module isn't currently bundled, presumably because of errors (though I'm not sure how to see what those errors are). 

So I decided to check out the [sony-visca](https://github.com/bitfocus/companion-module-sony-visca/) module and it turns out it is already compatible with V3, and under active development. Unfortunately, that module doesn't support TCP connections, which this module does (and which I need for my cameras). 

So I submitted a [PR](https://github.com/bitfocus/companion-module-sony-visca/pull/48) to add TCP functionality. There was also a conversation under [another issue](https://github.com/bitfocus/companion-module-sony-visca/issues/39). 

My PR adds the option of using the TCP protocol and after a lot of testing this weekend I can confirm it works well and does everything (and more) that I need it to do. 

After some careful consideration the maintainer(s) have decided to not accept my PR because it could begin to diverge that module away from being specific to Sony cameras. And whilst the idea of a creating generic VISCA module that works for all VISCA cameras seems attractive, it appears it's not without its downsides too.

So I guess this module will need updating to work for V3. And there are also quite a few useful features that are implemented in the Sony module that aren't in this one. 

There are also several other VISCA modules that are in need of similar modernisation if they are to survive beyond v2.

**Is anyone already working on a V3 upgrade for this module?** 

I'm happy to help out, and also would love to port some of the Sony module features if it would make sense to do so (don't know how we would decide), and reduce waste/duplicated effort where at all possible.

**Comment by DevilIris** [comment]
Hello Tony, I would suggest to add another module for Visca in TCP instead of trying to merge it with this module.

**Comment by tonypiper** [comment]
Hi @DevilIris. Thank you. Can you say more about your suggestion? Why would it be preferable to create another module, instead of submitting a PR to upgrade this one to V3?

**Comment by DevilIris** [comment]
Hello @tonypiper  Sorry for the late reply. Try to create a new Generic Visca PTZ Module because i don't know if the owner of this module currently still support this. Did you try to do a PR in this module?

**Comment by cyberblaststudios** [comment]
I currently have this PR in, which will convert this module to V3 @tonypiper https://github.com/bitfocus/companion-module-ptzoptics-visca/pull/26

**Comment by DevilIris** [comment]
Many Thanks for including this in the moduleDo you have a ETA for v3 release ? On 4 Jul 2023, at 14:24, Jaden Evanger ***@***.***> wrote:﻿
I currently have this PR in, which will convert this module to V3 @tonypiper #26

**Comment by cyberblaststudios** [comment]
> Many Thanks for including this in the moduleDo you have a ETA for v3 release ? On 4 Jul 2023, at 14:24, Jaden Evanger ***@***.***> wrote:﻿ I currently have this PR in, which will convert this module to V3 @tonypiper #26 —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

Unfortunately, I don't have a ETA on when it will be in the stable release. I think it will need to go through the beta release for a bit first, but I could be wrong.

**Comment by cyberblaststudios** [comment]
This is now in the stable v3 release.

**Comment by jsnyder886** [comment]
@cyberblaststudios Any idea when this module will be included in the betas again?

**Comment by Julusian** [comment]
It will be back in a few hours
