### ISSUE TITLE
Module does not show up in betas

### ISSUE THREAD

**Issue by jsnyder886** [bitfocus/companion-module-ptzoptics-visca#29]
Module is present in the 3.1.1 stable release (6229), but not in the beta release 3.2.0 (6442).

**Comment by jsnyder886** [comment]
@Julusian Any ideas on this?

**Comment by Julusian** [comment]
Companion is tripping up on this unexpected field https://github.com/bitfocus/companion-module-ptzoptics-visca/blob/09b53c1c2798c68e3690282d632eb313a10656c7/companion/manifest.json#L16-L18

**Comment by jsnyder886** [comment]
Is there anything I can do or do I just have to wait at this point?

**Comment by Julusian** [comment]
It will be back in a few hours
