### ISSUE TITLE
Add Gain Setting

### ISSUE THREAD

**Issue by ukiews** [bitfocus/companion-module-ptzoptics-visca#61]
Would it be possible to add Manual gain setting as one of the command options in the module?

81 01 04 0C 00 00 0p 0q FF [pq: Gain Positon(0~0x0E)]

**Comment by jswalden** [comment]
Yeah, this should be easy enough.

The docs I have (dated 20231027) say `pq` has range `[0x00, 0x07]`, tho, not `[0x00, 0x0E]`, so we'd need to figure out what the actual range is here to do this.  And if that range differs across cameras -- it might -- we'd need to determine precisely how to handle that discrepancy (as currently it's pretty much assumed all cameras behave identically).

In the meantime, tho, you can easily use the "Custom command" action to perform this stuff, without waiting on the module to provide it.

**Comment by ukiews** [comment]
For whatever reason I have issues setting Gain using the custom command action. I can set gain limit fine, but setting gain directly just causes the module to disconnect.

**Comment by jswalden** [comment]
@ukiews Can you flip on the "Log extra info during connection operations, for debugging purposes" setting, open up the debug console for the module (the ">_" link in the row for the instance on the Connections tab), then send the custom command and provide the resulting debug console output in a comment here?  The output should look something like this when all's said and done:

```
info: SEND: [81 07 00 00 FF]...
info: RECV: [90 41 FF]
info: Processing [81 07 00 00 FF] ACK in socket 1
info: RECV: [90 51 FF]
info: Completion in socket 1
```

except that if the module is disconnecting, something subtly different is going to show up rather than those two `RECV`s.

**Comment by ukiews** [comment]
Here is what I'm getting:

![Screenshot 2024-09-09 at 9 42 57 PM](https://github.com/user-attachments/assets/483c9c01-71aa-4102-82b3-9dd0f1e8b965)

**Comment by jswalden** [comment]
The camera is replying with `90 60 01 FF`?  That's extremely weird.  [PTZOptics documentation](https://ptzoptics.imagerelay.com/share/PTZOptics-G3-VISCA-over-IP-Commands) doesn't document that return message at all.  (You're using a PTZOptics camera, correct?)

I'm happy to add handling for this error return message -- assuming it encodes an error, at least (seems likely as it's not ACK or Completion) -- but I need to know what it's supposed to mean.  If you can file a support ticket with PTZOptics and get me more information about what it means and the circumstances under which it's sent -- and ideally get them to commit to documenting it in the next VISCA protocol documentation update -- then I can make some progress after that.

**Comment by ukiews** [comment]
No, I'm using Telycam. But everything else is working.
The command to set gain is also the same, with the exception of gain range.
https://www.manualslib.com/manual/1634709/Telycam-Tlc-300-Ip-12.html?page=11#manual

**Comment by ukiews** [comment]
any word on this?

**Comment by jswalden** [comment]
I've been occupied by other matters lately, sorry.

That documentation doesn't explain the meaning of a `90 60 01 FF` response: it's not listed in the "Error Messages" section, and it doesn't match the three-byte ACK or Completion messages.  Without documentation, I don't know what meaning it might have, and I can't be sure that it doesn't overlap PTZOptics VISCA messages to assign a non-PTZOptics meaning to it.  And the module policy is to support PTZOptics cameras, addressing other cameras only where it doesn't conflict with PTZOptics support.

I don't think this is suitable, given what is known right now, for fixing in a module for PTZOptics cameras.  I recommend you fork this module into one specifically for Telycam cameras, and then you can change the reply handling however you need to to handle this undocumented reply.  The actual changes you'd need to make shouldn't be terribly difficult.

**Comment by ukiews** [comment]
@jswalden Could you still add Gain as an Action? We are planning to switch to PTZOptics soon anyway. Having a gain setting allows for a quick way to set camera for specific lighting environment.
